baseurl = "https://jameswillia.ms/"
title = "James Williams"
theme = "book"

languageCode = "en-gb"

[[params]]
BookToC = true
BookMenuBundle = "/menu"

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
URL = "s3://jameswillia.ms?region=eu-west-2"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
