baseURL: http://jameswillia.ms/
title: James Williams
theme: hugo-book

languageCode: "en-gb"

menu:
  # before: []
  after:
    - name: GitHub
      url: "https://github.com/alex-shpak/hugo-book"
      weight: 10

params:
  BookToC: true
  BookMenuBundle: /menu
